config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :users, :except => [:new, :destroy]
  # patch '/users/:id/password', to: 'users#password', as: 'password'
  # post 'users/(/:id)/password', to: 'users#password', as: 'password'

  resources :houses, :except => [:show]

  resources :armies, :except => [:show] do
    collection do
      put 'update_multiple'
      put 'destroy_multiple'
      post 'edit_multiple'
      post 'import'
    end
  end
  get '/armies/:id/notes', to: 'armies#notes', as: 'army_note'
  get '/armies/:id/confirm', to: 'armies#confirm', as: 'army_confirm'

  # Login and logout routes
  get 'sso', to: 'sessions#sso', as: 'sso'

  post 'login', to: 'sessions#create', as: 'login'
  post 'logout', to: 'sessions#destroy', as: 'logout'
  get 'logout_sso', to: 'sessions#destroy_sso', as: 'logout_sso'

  resources :locations

  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get '/map', to: 'map#index'

  # get 'missions/', to: 'missions#index'
  # post 'missions/calculate', to: 'missions#calculate'
  # get 'missions/recipe', to: 'missions#recipe'

  get 'rep', to: 'reputations#index'
  post 'rep/change', to: 'reputations#change'

  get 'travel_calculator', to: 'travel_calculator#index'
  post 'travel_calculator/calculate', to: 'travel_calculator#calculate'
  # get 'travel_calculator/location_list', to: 'travel_calculator#location_list'

  # Render JSON lists for autocomplete

  get 'location_list', to: 'application#location_list'
  get 'location_list_en', to: 'application#location_list_en'
  get 'family_list', to: 'application#family_list'

  # Games and Tools

  get 'game', to: 'game#index'
  post 'game', to: 'game#set_active_game', as: 'set_active_game'

  resources :tools, :only => [:edit, :update]

  get '/ap-map', to: 'hex_map#index'

  resources :sectors, :except => [:show]
  delete '/sector_houses', to: 'sectors#sector_houses_destroy', as: 'delete_sector_houses'
  post '/sector_houses', to: 'sectors#sector_houses_create', as: 'create_sector_houses'

  post 'login_nemo', to: 'sessions#create_nemo', as: 'login_nemo'
  post 'login_master', to: 'sessions#create_master', as: 'login_master'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/notes', to: 'dashboard#notes', as: 'sector_note'
  post 'dashboard/notes', to: 'dashboard#notes_save', as: 'sector_note_save'
  post 'dashboard/resources/:id/spend', to: 'dashboard#spend_resources', as: 'spend_resources'
  post 'dashboard/resources/:id/efficiencies', to: 'dashboard#change_efficiencies', as: 'change_efficiencies'
  get 'dashboard/tech/:id', to: 'dashboard#tech', as: 'dashboard_tech'

  resources :techs, :except => [:show]
  get '/techs/:id/confirm', to: 'techs#confirm', as: 'tech_confirm'

  get '/designs/size_select', to: 'designs#size_select', as: 'size_select_design'
  post '/designs/new', to: 'designs#new', as: 'new_design'
  resources :designs, :except => [:new]
  get '/designs/:id/confirm', to: 'designs#confirm', as: 'design_confirm'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/design.rb
class Design < ApplicationRecord
  belongs_to :house

  validates :name, presence: true
  validates :size, :inclusion => {:in => [2,4,8,12,20,50,100,500]}


  $ship_sizes = {
    2 => 'Escuadrón de cazas',
    4 => 'Corbeta',
    8 => 'Fragata',
    12 => 'Destructor',
    20 => 'Crucero',
    50 => 'Acorazado',
    100 => 'Titán',
    500 => 'Coloso estelar'
  }

  $modules = {:none=>"Vacío"}.merge($tech_types.select {|k,v| k[0,4] == ('navy' || 'misc')})

  $systems = $tech_types.select {|k,v| k[0,4] == ('sys_' || 'misc')}

  $hp_per_mod = 5
  $dmg_per_las = 2
  $dmg_per_mass = 1
  $dmg_per_tech = 0.1
  $def_per_shield = 1
  $def_per_shield_tech = 0.1
  $hp_per_armor = 5
  $hp_per_armor_tech = 0.1

  def ship_type
    $ship_sizes[self.size]
  end

  def mod_navy_las
    [self.modules.flatten.count('navy_las'),self.modules.flatten.index('navy_las').nil? ? 0 : (self.modules.flatten[self.modules.flatten.index('navy_las') + 1]).to_i]
  end

  def mod_navy_mass
    [self.modules.flatten.count('navy_mass'),self.modules.flatten.index('navy_mass').nil? ? 0 : (self.modules.flatten[self.modules.flatten.index('navy_mass') + 1]).to_i]
  end

  def mod_navy_armor
    [self.modules.flatten.count('navy_armor'),self.modules.flatten.index('navy_armor').nil? ? 0 : (self.modules.flatten[self.modules.flatten.index('navy_armor') + 1]).to_i]
  end

  def mod_navy_shields
    [self.modules.flatten.count('navy_shields'),self.modules.flatten.index('navy_shields').nil? ? 0 : (self.modules.flatten[self.modules.flatten.index('navy_shields') + 1]).to_i]
  end

  def mod_misc
    self.modules.flatten.count('misc')
  end

  def mod_none
    self.modules.flatten.count('none')
  end

  def desp
    self.size * 10
  end

  def hp
    self.size * $hp_per_mod + (self.mod_navy_armor[0].to_i * $hp_per_armor * (1 + (self.mod_navy_armor[1].to_f - 1) * $hp_per_armor_tech))
  end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :check_user
  before_action :correct_user, only: [:edit, :update, :confirm, :destroy]
  before_action :set_design, only: [:show, :edit, :update, :confirm, :destroy]


  def index
    if current_user.is_master? || current_user.is_admin?
      @designs = Design.all.order(:id)
    else
      @designs = Design.where(house: current_user.house).order(:id)
    end
  end

  def edit
    @size = @design.size
    @house = @design.house
    if @design.active == true
      respond_to do |format|
        format.js { render 'permissions' }
      end
    end
  end

  def show
    @size = @design.size
    @house = @design.house
  end

  def size_select
    if current_user.is_master? || current_user.is_admin?
      @dock_lvl = 7
    else
      @dock_lvl = ( current_user.house.techs.where(tech_type: 'dock').order(lvl: :desc).first.try(:lvl) || 1 ) + 1
    end
    @available_sizes = $ship_sizes.first(@dock_lvl)
    @active_houses = House.where(name: 'Inactivo').order(:hid).map { |house| [house.name, house.id] }.concat(House.where(active: true).order(:name).map { |house| [house.name, house.id] })
  end

  def new
    @size = params[:size]
    if current_user.is_master? || current_user.is_admin?
      @house = House.find(params[:house_id])
    else
      @house = current_user.house
    end
    @design = Design.new
  end

  def create
    @m = params[:design][:modules]
    @design = Design.new(design_params)

    respond_to do |format|
      if @design.save && @design.update(modules: @m)
        format.html { redirect_to designs_url, success: 'Diseño añadido correctamente.' }
      else
        format.html { redirect_to designs_url, danger: @design.errors }
      end
    end
  end

  def destroy
    if (@design.active == false || params[:design][:confirm] == "DELETE") then
      @design.destroy
      respond_to do |format|
        format.html { redirect_to designs_url, danger: 'Diseño borrado.' }
      end
    else
      respond_to do |format|
        format.html { redirect_to designs_url, danger: 'Acción cancelada, por favor, confirma correctamente el borrado' }
      end
    end
  end

  def update
    @m = params[:design][:modules]

    respond_to do |format|
      if @design.update(design_params)
        unless @m.nil?
          @design.update(modules: @m)
        end
        format.html { redirect_to designs_url, success: 'Diseño editado  correctamente.' }
      else
        format.html { redirect_to designs_url, danger: @design.errors }
      end
    end
  end

  def confirm
    respond_to do |format|
      format.js
      format.html { redirect_to designs_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    def check_user
      if current_user.nil?
        flash[:danger] = "Por favor, inicia sesión."
        redirect_to root_url
      end
    end

    def correct_user
      @design = Design.find(params[:id])
      unless current_user.is_master? || current_user.is_admin? || (current_user.house == @design.house)
        respond_to do |format|
          format.js { render 'permissions' }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:name, :desc, :notes, :size, :house_id, :active, :sys_ftl, :sys_engine, :sys_sensors)
    end

end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_confirm.html.erb
<%= form_with(model: design, method: :delete, local: true) do |form| %>
  <div class="modal-header">
    <h5 class="modal-title" id="Title">Confirmar borrado</h5>
    <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="form-group">
      Para borrar el diseño <strong><%= @design.name %></strong> de los <%= @design.house.name %>, por favor escribe "DELETE" en el siguiente campo:
    </div>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <div class="input-group-text"><i class="fas fa-trash-alt"></i>&nbsp;</div>
      </div>
      <%= form.text_field :confirm, class: "form-control" %>
    </div>
    <div class="input-group mb-3">
      <%= form.submit 'Eliminar diseño', class: "btn btn-primary" %>
    </div>
    <div class="input-group mb-3">
      Este diseño está en uso en las siguientes naves:
    </div>
  </div>
<% end %>

app/views/designs/_form.html.erb
<%= form_with(model: design, local: true) do |form| %>
  <div class="modal-header">
    <h5 class="modal-title" id="Title"><%= design.name.nil? ? 'Nuevo diseño - ' + @house.name : design.name + ' - ' + design.house.name %></h5>
    <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <% if design.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(design.errors.count, "error") %> prohibited this house from being saved:</h2>
        <ul>
          <% design.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div id= "data" class="col-md-6 right-separator"">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <div class="input-group-text"><i class="fas fa-pencil-ruler"></i>&nbsp;</div>
          </div>
          <%= form.text_field :name, class: "form-control", value: @design.name, placeholder: "Nombre" %>
        </div>
        <div class="input-group mb-3 w-100">
          <%= form.text_area :desc, rows: 5, id: 'desc', class: "custom-control w-100", placeholder: 'Descripción' %>
        </div>
        <% if current_user.is_master? %>
          <div class="input-group mb-3 w-100">
            <%= form.text_area :notes, rows: 5, id: 'notes', class: "custom-control w-100", placeholder: 'Notas del master', style: 'background: lightyellow' %>
          </div>
        <% end %>
        <div>Desplazamiento: <span id="dis">0</span></div>
        <div>Estructura: <span id="str">0</span></div>
        <div>Potencial de fuego: <span id="atk">0</span></div>
        <div>Potencial de defensa: <span id="def">0</span></div>
        <div>Sensores: <span id="sen">0</span></div>
        <div>Sigilo: <span id="ste">0</span></div>
        <div>Motores convencionales: <span id="eng">0</span></div>
        <div>Motores FTL: <span id="ftl">0</span></div>
      </div>
      <div class="col-md-5 ml-3">
        <% if current_user.is_master? %>
          <div class="form-group form-inline">
            <div class="input-group mb-3 ml-0">
              <div class="input-group-prepend">
                <div class="input-group-text">¿Activo?</div>
              </div>
              <div class="form-check checkbox-slider--a checkbox-slider-lg">
                <label>
                  <%= form.check_box :active, default: 'no', id: 'active' %><span>&nbsp;</span>
                </label>
              </div>
            </div>
          </div>
        <% end %>

        <% if @design.active == true %>
          <%= render 'mod_descriptor' %>
        <% else %>
          <%= render 'mod_selector', form: form %>
        <% end %>
      </div>
    </div>

    <div class="input-group mb-3">
      <%= form.text_field :house_id, class: 'd-none', value: @house.id %>
      <%= form.text_field :size, class: 'd-none',value: @size %>
      <% if @design.active == false || current_user.is_master? %>
        <%= form.submit class: "btn btn-primary", id: "submit" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/designs/_mod_descriptor.erb
<div class="row">
  <h3>Sistemas</h3>
</div>
<div class="row">
  <% $systems.each do |k,v| %>
    <div class="float-left mr-4 mb-2">
      <div id="sys_type_sys_ftl-dd-placeholder" class="dd-container" style="width: 56px;">
        <div style="border-radius:2px; border:solid 1px #ccc; position:relative; cursor:pointer;" style="width: 56px; background: rgb(238, 238, 238) none repeat scroll 0% 0%;">
          <img style="vertical-align:middle; float:left; margin-right:5px; max-width:64px;" title="<%= v %>" src="<%= image_url('tech/' + k.to_s) %>">
          <label style="font-weight:bold; font-size: 30px; margin-left: -40px; color: white"><%= @house.techs.where(tech_type: k.to_s).order(lvl: :desc).first.try(:lvl) || 1 %></label>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <h3>Módulos</h3>
</div>
<div class="row">
  <% for i in 1..@size.to_i do %>
    <div class="float-left mr-4 mb-2">
      <div id="sys_type_sys_ftl-dd-placeholder" class="dd-container" style="width: 56px;">
        <div style="border-radius:2px; border:solid 1px #ccc; position:relative; cursor:pointer;" style="width: 56px; background: rgb(238, 238, 238) none repeat scroll 0% 0%;">
          <img style="vertical-align:middle; float:left; margin-right:5px; max-width:64px;" title="<%= $modules[(@design.modules[(i - 1)*2][0].to_sym)] %>" src="<%= image_url('tech/' + @design.modules[(i - 1)*2][0]) %>">
          <label style="font-weight:bold; font-size: 30px; margin-left: -40px; color: white"><%= @house.techs.where(tech_type: (@design.modules[(i - 1)*2][0].to_sym)).order(lvl: :desc).first.try(:lvl) || 1 %></label>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/designs/_mod_selector.erb
<div class="row">
  <h3>Sistemas</h3>
</div>
<div class="row">
  <% $systems.each do |k,v| %>
    <div class="float-left mr-4 mb-2">
      <%= form.select k, options_for_select([[@house.techs.where(tech_type: k.to_s).order(lvl: :desc).first.try(:lvl) || 1,k,{'data-imagesrc' => image_url('tech/' + k.to_s), 'data-description' => '', 'data-imagetitle' => v}],['&nbsp;',:none,{'data-imagesrc' => image_url('tech/none'), 'data-description' => '', 'data-imagetitle' => 'Vacío'}]]), {}, {class: 'system', id: 'sys_type_' + k.to_s} %>
      <%= form.text_field k, id: 'sys_lvl_' + k.to_s, class: 'd-none' %>
    </div>
  <% end %>
</div>
<div class="row">
  <h3>Módulos</h3>
</div>
<div class="row">
  <% for i in 1..@size.to_i do %>
    <div class="float-left mr-4 mb-2">
      <%= form.select "modules[][", options_for_select($modules.map {|k,v| [((k == :misc || k == :none) ? '&nbsp;' : (@house.techs.where(tech_type: k.to_s).order(lvl: :desc).first.try(:lvl) || 1)),k,{'data-imagesrc' => image_url('tech/' + k.to_s), 'data-description' => '', 'data-imagetitle' => v}]},@design.modules.nil? ? :none : @design.modules[ (i - 1) * 2]), {}, {class: 'module', id: 'mod_type_' + i.to_s} %>
      <%= form.text_field "modules[][", id: 'mod_lvl_' + i.to_s, class: 'd-none' %>
    </div>
  <% end %>
</div>

app/views/designs/_size_select.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="Title"><%= 'Nuevo diseño' %></h5>
  <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= form_with url: new_design_path, remote: true do |form| %>
  <div class="modal-body">
    <div class="form-group">
      <%= form.select "size", options_for_select(@available_sizes.map {|k,v| [v,k.to_s,{'data-imagesrc' => image_url('designs/' + k.to_s + 'm'), 'data-imagetitle' => v, 'data-description' => k.to_s + ' módulos'}]}), {}, {id: 'size_select'} %>
    </div>
    <% if current_user.is_master? || current_user.is_admin? %>
      <div class="form-group form-inline">
        <div class="input-group">
          <div class="input-group-prepend">
            <div class="input-group-text"><i class="fas fa-flag"></i>&nbsp;</div>
          </div>
          <%= form.select :house_id, options_for_select(@active_houses), {}, {class: "custom-select"} %>
        </div>
      </div>
    <% end %>
    <div class="form-group form-inline">
      <%= form.submit 'Seleccionar tamaño', class: "btn btn-primary", id: "select" %>
    </div>
  </div>
<% end %>

app/views/designs/confirm.js.erb
$('#design-content').html("<%= j render 'confirm', design: @design %>");
$('#designModal').modal('show');

app/views/designs/edit.js.erb
$('#design-content').html("<%= j render 'form', design: @design %>");
$('#designModal').modal('show');
$('.module').ddslick({
  width: '56px',
  imposeDesc: true,
  onSelected: function(data){
    var id = $(data.original[0].id.split("_")).get(-1);
    var lvl = data.selectedData.text;
    $('#mod_lvl_' + id).val(lvl);
    }
});
$('.system').ddslick({
  width: '56px',
  imposeDesc: true,
  onSelected: function(data){
    var id = $(data.original[0].id.split("_")).get(-1);
    var lvl = data.selectedData.text;
    $('#sys_lvl_sys_' + id).val(lvl);
    }
});

app/views/designs/index.html.erb
<% provide(:title, $all_tools.find_by(path: request.fullpath).title) %>
<% provide(:icon, $all_tools.find_by(path: request.fullpath).icon) %>

<div class="tool-title">
    <i class="white <%= yield(:icon) %>"></i>
    <%= yield(:title) %>
</div>

<%= current_user.house.name %>

<div>
  <table class="table table-dark table-striped table-borderless table-hover table-sm table-responsive sortable">
    <caption>Lista de diseños</caption>
      <thead>
        <tr>
          <% if current_user.try(:is_master?) %>
            <th scope="col">Jugador <i class="fas fa-sort"></i></th>
            <th scope="col">Facción <i class="fas fa-sort"></i></th>
          <% end %>
          <th scope="col" colspan="2">Tamaño <i class="fas fa-sort"></i></th>
          <th scope="col">Nombre <i class="fas fa-sort"></i></th>
          <th scope="col" colspan="2">Energía</th>
          <th scope="col" colspan="2">Incercial</th>
          <th scope="col" colspan="2">Armadura</th>
          <th scope="col" colspan="2">Escudos</th>
          <th scope="col">Misc</th>
          <th scope="col">Motores</th>
          <th scope="col">FTL</th>
          <th scope="col">Sensores</th>
          <th scope="col">Sigilo</th>
        </tr>
      </thead>
      <tbody>
        <% @designs.each do |design| %>
          <tr class="<%= design.active == false ? 'destroyed' : '' %>">
            <% if current_user.try(:is_master?) %>
              <td><%= design.house.users.pluck(:player).join(', ') %></td>
              <td><%= design.house.name %></td>
            <% end %>
            <td><%= design.ship_type %></td>
            <td><%= ' (' + design.size.to_s + ')' %></td>
            <td><%= design.name %></td>
            <td><%= design.mod_navy_las[0] %></td>
            <td><%= design.mod_navy_las[1] %></td>
            <td><%= design.mod_navy_mass[0] %></td>
            <td><%= design.mod_navy_mass[1] %></td>
            <td><%= design.mod_navy_armor[0] %></td>
            <td><%= design.mod_navy_armor[1] %></td>
            <td><%= design.mod_navy_shields[0] %></td>
            <td><%= design.mod_navy_shields[1] %></td>
            <td><%= design.mod_misc %></td>
            <td><%= design.mod_misc %></td>
            <td><%= design.mod_misc %></td>
            <td><%= design.mod_misc %></td>
            <td><%= design.mod_misc %></td>
            <td>
              <% if design.active == true %>
                <%= link_to '', design_path(design), remote: true, class: 'fas fa-eye white' %>
              <% else %>
                <%= link_to '', edit_design_path(design), remote: true, class: 'fas fa-edit white' %>
              <% end %>
            </td>
            <td>
              <% if design.active == true && current_user.is_master? %>
                <%= link_to '', design_confirm_path(design), remote: true, class: 'fas fa-trash-alt white' %>
              <% elsif design.active == false %>
                <%= link_to '', design, method: :delete, class: 'fas fa-trash-alt white' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

<div><%= link_to '<i class="fas fa-plus-circle"></i> Añadir diseño'.html_safe, size_select_design_path, remote:true, class: "btn btn-primary"%></div>

<!-- Modal -->

<div class="modal fade" id="designModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div id='design-content' class="modal-content bg-dark">
    </div>
  </div>
</div>

app/views/designs/new.js.erb
$('#design-content').html("<%= j render 'form', design: @design %>");
$('#designModal').modal('show');
$('.module').ddslick({
  width: '56px',
  imposeDesc: true,
  onSelected: function(data){
    var id = $(data.original[0].id.split("_")).get(-1);
    var lvl = data.selectedData.text;
    $('#mod_lvl_' + id).val(lvl);
    }
});
$('.system').ddslick({
  width: '56px',
  imposeDesc: true,
  onSelected: function(data){
    var id = $(data.original[0].id.split("_")).get(-1);
    var lvl = data.selectedData.text;
    $('#sys_lvl_sys_' + id).val(lvl);
    }
});

app/views/designs/permissions.js.erb
$('.tool-title').parent().prepend('<div class="container mx-auto text-center alert alert-danger" style="">No tienes permisos para acceder a este elemento.</div>')

app/views/designs/show.js.erb
$('#design-content').html("<%= j render 'form', design: @design %>");
$('#designModal').modal('show');
$('#data :input').prop("disabled", true);

app/views/designs/size_select.js.erb
$('#design-content').html("<%= j render 'size_select' %>");
$('#designModal').modal('show');
$('#size_select').ddslick();