config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :users, :except => [:new, :destroy]
  # patch '/users/:id/password', to: 'users#password', as: 'password'
  # post 'users/(/:id)/password', to: 'users#password', as: 'password'

  resources :houses, :except => [:show]

  resources :armies, :except => [:show] do
    collection do
      put 'update_multiple'
      put 'destroy_multiple'
      post 'edit_multiple'
      post 'import'
    end
  end
  get '/armies/:id/notes', to: 'armies#notes', as: 'army_note'
  get '/armies/:id/confirm', to: 'armies#confirm', as: 'army_confirm'

  # Login and logout routes
  get 'sso', to: 'sessions#sso', as: 'sso'

  post 'login', to: 'sessions#create', as: 'login'
  post 'logout', to: 'sessions#destroy', as: 'logout'
  get 'logout_sso', to: 'sessions#destroy_sso', as: 'logout_sso'

  resources :locations

  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get '/map', to: 'map#index'

  # get 'missions/', to: 'missions#index'
  # post 'missions/calculate', to: 'missions#calculate'
  # get 'missions/recipe', to: 'missions#recipe'

  get 'rep', to: 'reputations#index'
  post 'rep/change', to: 'reputations#change'

  get 'travel_calculator', to: 'travel_calculator#index'
  post 'travel_calculator/calculate', to: 'travel_calculator#calculate'
  # get 'travel_calculator/location_list', to: 'travel_calculator#location_list'

  # Render JSON lists for autocomplete

  get 'location_list', to: 'application#location_list'
  get 'location_list_en', to: 'application#location_list_en'
  get 'family_list', to: 'application#family_list'

  # Games and Tools

  get 'game', to: 'game#index'
  post 'game', to: 'game#set_active_game', as: 'set_active_game'

  resources :tools, :only => [:edit, :update]

  get '/ap-map', to: 'hex_map#index'

  resources :sectors, :except => [:show]
  delete '/sector_houses', to: 'sectors#sector_houses_destroy', as: 'delete_sector_houses'
  post '/sector_houses', to: 'sectors#sector_houses_create', as: 'create_sector_houses'

  post 'login_nemo', to: 'sessions#create_nemo', as: 'login_nemo'
  post 'login_master', to: 'sessions#create_master', as: 'login_master'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/notes', to: 'dashboard#notes', as: 'sector_note'
  post 'dashboard/notes', to: 'dashboard#notes_save', as: 'sector_note_save'
  post 'dashboard/resources/:id/spend', to: 'dashboard#spend_resources', as: 'spend_resources'
  post 'dashboard/resources/:id/efficiencies', to: 'dashboard#change_efficiencies', as: 'change_efficiencies'
  get 'dashboard/tech/:id', to: 'dashboard#tech', as: 'dashboard_tech'

  resources :techs, :except => [:show]
  get '/techs/:id/confirm', to: 'techs#confirm', as: 'tech_confirm'

  get '/designs/size_select', to: 'designs#size_select', as: 'size_select_design'
  post '/designs/new', to: 'designs#new', as: 'new_design'
  resources :designs, :except => [:new]
  get '/designs/:id/confirm', to: 'designs#confirm', as: 'design_confirm'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :master_user, except: [:index, :notes, :notes_save, :tech]
  before_action :set_resource, except: [:index, :notes, :notes_save, :tech]

  def index
    if current_user.nil?
      flash[:danger] = "Por favor, inicia sesión."
      redirect_to root_url
    elsif current_user.is_master? || current_user.is_admin?
      @civilizations = House.where(active: true)
    else
      @resource = current_user.house.resource
      @systems = current_user.house.systems
    end
  end

  # GET /dashboard/1/notes
  def notes
    @sectorhouse = SectorHouse.find(params[:id])
    respond_to do |format|
      if @sectorhouse.house.users.exists?(id: current_user.id) || current_user.is_master? || current_user.is_admin?
        format.js
      else
        format.js { render 'layouts/_alert_box', :locals => { alert: 'danger', message: 'No tienes permiso para acceder a este elemento' } }
      end
    end
  end

  def notes_save
    @sectorhouse = SectorHouse.find(params[:id])
    respond_to do |format|
      if @sectorhouse.house.users.exists?(id: current_user.id) || current_user.is_master? || current_user.is_admin?
        if @sectorhouse.update(notes: params[:notes])
          format.html { redirect_to request.referrer, success: 'Notas editadas correctamente.' }
        else
          format.html { redirect_to request.referrer, danger: @sector.errors }
        end
      else
        format.js { render 'layouts/_alert_box', :locals => { alert: 'danger', message: 'No tienes permiso para acceder a este elemento' } }
      end
    end
  end

  def spend_resources
    @resource.ic -= spend_resources_params[:ic_spend].to_i
    @resource.rp -= spend_resources_params[:rp_spend].to_i
    @resource.cp -= spend_resources_params[:cp_spend].to_i
    respond_to do |format|
      if @resource.save
        format.html { redirect_to request.referrer, success: 'Recursos gastados correctamente.' }
      else
        format.html { redirect_to request.referrer, danger: @resource.errors }
      end
    end
  end

  def change_efficiencies
    respond_to do |format|
      if @resource.update(change_efficiencies_params)
        format.html { redirect_to request.referrer, success: 'Eficiencias cambiadas correctamente.' }
      else
        format.html { redirect_to request.referrer, danger: @resource.errors }
      end
    end
  end

  def tech
    if current_user.is_master? || current_user.is_admin?
      @techs = House.find(params[:id]).techs
      @civ = House.find(params[:id])
    else
      @techs = current_user.house.techs
      @civ = current_user.house
    end

    respond_to do |format|
      format.js
    end
  end

private
  def set_resource
    @resource = Resource.find(params[:id])
  end

# Check if user is master or admin
  def master_user
    if current_user.nil?
      flash[:danger] = "Por favor, inicia sesión."
      redirect_to root_url
    elsif !current_user.is_master? && !current_user.is_admin?
      redirect_to(root_url)
      flash[:danger] = "No tienes permisos para acceder a esta página."
    end
  end

  def spend_resources_params
    params.permit(:ic_spend, :rp_spend, :cp_spend)
  end

  def change_efficiencies_params
    params.permit(:ic_bonus, :rp_bonus, :cp_bonus)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_controls.html.erb
<div class="card bg-warning">
  <div class="card-body">
    <div class="card-text text-dark">
      <div class="float-left mr-3">
        <%= form_with(url: spend_resources_path(@resource), remote: true) do |form| %>
          <div class="input-group">
            <%= form.button 'Gastar recursos', value: 'spend', class: 'btn btn-danger m-auto' %>
          </div>

          <div class="input-group">
            <div class="input-group-prepend">
              <div style="width: 45px" class="input-group-text"><i class="fas fa-industry"></i>&nbsp;</div>
            </div>
            <%= form.number_field :ic_spend, style: 'width: 120px', class: "custom-control mr-1", placeholder: "±ICs", max: @resource.ic %>
          </div>

          <div class="input-group">
            <div class="input-group-prepend">
              <div style="width: 45px" class="input-group-text"><i class="fas fa-flask"></i>&nbsp;</div>
            </div>
            <%= form.number_field :rp_spend, style: 'width: 120px', class: "custom-control mr-1", placeholder: "±RPs", max: @resource.rp %>
          </div>

          <div class="input-group">
            <div class="input-group-prepend">
              <div style="width: 45px" class="input-group-text"><i class="fas fa-chess-king"></i>&nbsp;</div>
            </div>
            <%= form.number_field :cp_spend, style: 'width: 120px', class: "custom-control mr-1", placeholder: "±CPs", max: @resource.cp %>
          </div>
        <% end %>
      </div>

      <div class="float-left">
        <%= form_with(url: change_efficiencies_path(@resource), remote: true) do |form| %>
          <div class="input-group">
            <%= form.button 'Cambiar eficiencias', value: 'spend', class: 'btn btn-danger m-auto' %>
          </div>
          <div class="input-group">
            <div class="input-group-prepend">
              <div style="width: 85px" class="input-group-text"><i class="fas fa-industry"></i>&nbsp;<i class="fas fa-percentage"></i></div>
            </div>
            <%= form.number_field :ic_bonus, style: 'width: 120px', class: "custom-control mr-1", value: @resource.ic_bonus, min: 0, step: 0.01 %>
          </div>

          <div class="input-group">
            <div class="input-group-prepend">
              <div style="width: 85px" class="input-group-text"><i class="fas fa-flask"></i>&nbsp;<i class="fas fa-percentage"></i></div>
            </div>
            <%= form.number_field :rp_bonus, style: 'width: 120px', class: "custom-control mr-1", value: @resource.rp_bonus, min: 0, step: 0.01 %>
          </div>

          <div class="input-group">
            <div class="input-group-prepend">
              <div style="width: 85px" class="input-group-text"><i class="fas fa-chess-king"></i>&nbsp;<i class="fas fa-percentage"></i></div>
            </div>
            <%= form.number_field :cp_bonus, style: 'width: 120px', class: "custom-control mr-1", value: @resource.cp_bonus, min: 0, step: 0.01 %>
          </div>

          <div class="input-group">
            <div class="input-group-prepend">
              <div style="width: 85px" class="input-group-text">Global&nbsp;<i class="fas fa-percentage"></i></div>
            </div>
            <%= form.number_field :cp_bonus, style: 'width: 120px', class: "custom-control mr-1", value: @resource.cp_bonus, min: 0, step: 0.01 %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_dashboard.html.erb
<div class="card bg-info col-6">
  <div class="card-body">
    <div class="card-text">
      <div class="float-left mr-1">
        <p><i class="fas fa-industry"></i> : <%= @resource.ic %></p>
        <p><i class="fas fa-flask"></i> : <%= @resource.rp %></p>
        <p><i class="fas fa-chess-king"></i> : <%= @resource.cp %></p>
      </div>
      <div class="float-left mr-1">
        <p><span class="text-danger">(<%= @resource.ic_prod %> p/d)</span></p>
        <p><span class="text-danger">(<%= @resource.rp_prod %> p/d)</span></p>
        <p><span class="text-danger">(<%= @resource.cp_prod %> p/d)</span></p>
      </div>
      <div class="float-left mr-1">
        <p><i class="fas fa-percentage"></i> : <%= @resource.ic_bonus.truncate() * 100 %> %</p>
        <p><i class="fas fa-percentage"></i> : <%= @resource.rp_bonus.truncate() * 100 %> %</p>
        <p><i class="fas fa-percentage"></i> : <%= @resource.cp_bonus.truncate() * 100 %> %</p>
      </div>
      <div class="float-right mr-1">
        <p>Eficiencia global : <%= @resource.efficiency.truncate() * 100 %> %</p>
        <p>Tamaño de flota : 999999 módulos</p>
        <p>Población total : <%= @resource.house.systems.pluck('SUM(ic_slots), SUM(rp_slots), SUM(cp_slots), SUM(mc_slots)').flatten.sum {|e| e.to_i} * 1000 %> millones </p>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_dashboard_table.html.erb
<div class="card bg-info m-auto col-6">
  <div class="card-body">
    <div class="card-text">
      <div class="float-left mr-1">
        <p><i class="fas fa-industry"></i> : <%= @resource.ic %></p>
        <p><i class="fas fa-flask"></i> : <%= @resource.rp %></p>
        <p><i class="fas fa-chess-king"></i> : <%= @resource.cp %></p>
      </div>
      <div class="float-left mr-1">
        <p><span class="text-danger">(<%= @resource.ic_prod %> p/d)</span></p>
        <p><span class="text-danger">(<%= @resource.rp_prod %> p/d)</span></p>
        <p><span class="text-danger">(<%= @resource.cp_prod %> p/d)</span></p>
      </div>
      <div class="float-left mr-1">
        <p><i class="fas fa-percentage"></i> : <%= @resource.ic_bonus.truncate() * 100 %> %</p>
        <p><i class="fas fa-percentage"></i> : <%= @resource.rp_bonus.truncate() * 100 %> %</p>
        <p><i class="fas fa-percentage"></i> : <%= @resource.cp_bonus.truncate() * 100 %> %</p>
      </div>
      <div class="float-right mr-1">
        <p>Eficiencia global : <%= @resource.efficiency.truncate() * 100 %> %</p>
        <p>Tamaño de flota : 999999 módulos</p>
        <p>Población total : <%= @resource.house.systems.pluck('SUM(ic_slots), SUM(rp_slots), SUM(cp_slots), SUM(mc_slots)').flatten.sum {|e| e.to_i} * 1000 %> millones </p>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_notes.html.erb
<%= form_with(url: sector_note_save_path, local: true) do |form| %>
  <div class="modal-header">
    <h5 class="modal-title" id="Title">Notas de <%= sectorhouse.sector.name + ' (' + sectorhouse.sector.q.to_s + ',' + sectorhouse.sector.r.to_s + ')' %></h5>
    <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="form-group">
      <%= form.number_field :id, class: "form-control d-none", value: sectorhouse.id %>
      <%= form.text_area :notes, class: "form-control", rows: 5, value: sectorhouse.notes, placeholder: "Notas" %>
    </div>
    <%= form.button '<i class="fa fa-check-circle" aria-hidden="true"></i>'.html_safe, class: "btn btn-success btn-text-area" %>
  </div>
<% end %>

app/views/dashboard/_systems_table.html.erb
<div class="tab-content mt-3" id="nav-tabContent">
  <div>
    <table class="table table-dark table-striped table-borderless table-hover table-sm table-responsive sortable">
      <caption>Lista de sistemas</caption>
        <thead>
          <tr>
            <th scope="col">Sistema <i class="fas fa-sort"></i></th>
            <th scope="col">Slots <i class="fas fa-sort"></i></th>
            <th scope="col">libres <i class="fas fa-sort"></i></th>
            <th scope="col">IC <i class="fas fa-sort"></i></th>
            <th scope="col">p/d <i class="fas fa-sort"></i></th>
            <th scope="col">RP <i class="fas fa-sort"></i></th>
            <th scope="col">p/d <i class="fas fa-sort"></i></th>
            <th scope="col">CP <i class="fas fa-sort"></i></th>
            <th scope="col">p/d <i class="fas fa-sort"></i></th>
            <th scope="col">Otros <i class="fas fa-sort"></i></th>
            <th scope="col">Descripción <i class="fas fa-sort"></i></th>
            <% if current_user.try(:is_master?) then %>
              <th scope="col">Civilización <i class="fas fa-sort"></i></th>
            <% end %>
              <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @systems.each do |system| %>
            <tr>
              <td><%= system.sector.name + ' (' + system.sector.q.to_s + ',' + system.sector.r.to_s + ')' %></td>
              <td><%= system.slots %></td>
              <td><%= system.slots_free %></td>
              <td><%= system.ic_slots %></td>
              <td><%= system.ic_prod %></td>
              <td><%= system.rp_slots %></td>
              <td><%= system.rp_prod %></td>
              <td><%= system.cp_slots %></td>
              <td><%= system.cp_prod %></td>
              <td><%= system.mc_slots %></td>
              <td><%= system.sector.desc %></td>
              <% if current_user.try(:is_master?) then %>
                <td><%= system.try(:user).try(:house).try(:name) %></td>
                <td><%= link_to '', edit_sector_path(system.sector), remote: true, class: 'fas fa-edit white' %></td>
              <% end %>
              <td>
                <% sectorhouse = SectorHouse.where(sector: system.sector).find_by(house: system.house)%>
                <%= link_to '', sector_note_path(id: sectorhouse), remote:true, class: 'fas fa-sticky-note ' + (sectorhouse.notes.blank? ? 'white' : 'text-warning') %>
              </td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/dashboard/_techs.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="Title">Tecnología de los <%= @civ.name %></h5>
  <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <nav>
    <div class="nav nav-pills mb-1" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-main-tab" data-toggle="tab" href="#nav-main" role="tab" aria-controls="nav-main" aria-selected="false">Principales</a>
      <a class="nav-item nav-link" id="nav-misc-tab" data-toggle="tab" href="#nav-misc" role="tab" aria-controls="nav-misc" aria-selected="false">Otras</a>
      <a class="nav-item nav-link" id="nav-old-tab" data-toggle="tab" href="#nav-old" role="tab" aria-controls="nav-old" aria-selected="false">Obsoletas</a>
      <% if current_user.try(:is_master?) then %>
        <a class="nav-item nav-link btn-success ml-5" id="nav-add-tab" data-toggle="tab" href="#nav-add" role="tab" aria-controls="nav-old" aria-selected="false"><i class="fas fa-plus-circle"></i> Añadir Tecnología</a>
      <% end %>
    </div>
  </nav>

  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade active show" id="nav-main" role="tabpanel" aria-labelledby="nav-main-tab">
      <table class="table table-responsive table-dark table-striped table-borderless table-hover table-sm table-responsive sortable">
        <caption>Lista de tecnologías</caption>
        <thead>
          <tr>
            <th scope="col">Rama</th>
            <th scope="col">Nivel</th>
            <th scope="col">Nombre</th>
            <th class='w-100' scope="col">Descripción</th>
          </tr>
        </thead>
        <tbody>
          <% $tech_types.reject{|x| x == :misc}.each do |x| %>
            <tr>
              <td>
                <%= image_tag('/assets/tech/' + x[0].to_s, title: x[1].to_s) %>
              </td>
              <td class="align-middle">
                <span class="font-weight-bold" style="font-size: 2em">
                  <%= @techs.where(tech_type: x).order(lvl: :desc).first.try(:lvl) %>
                </span>
              </td>
              <td class="align-middle">
                <%= @techs.where(tech_type: x).order(lvl: :desc).first.try(:name) %>
              </td>
              <td class="align-middle">
                <%= @techs.where(tech_type: x).order(lvl: :desc).first.try(:desc) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="tab-pane fade" id="nav-misc" role="tabpanel" aria-labelledby="nav-misc-tab">
      <table class="table table-responsive table-dark table-striped table-borderless table-hover table-sm table-responsive sortable">
        <caption>Otras tecnologías</caption>
        <thead>
          <tr>
            <th scope="col">Rama</th>
            <th scope="col">Nivel</th>
            <th scope="col">Nombre</th>
            <th class='w-100' scope="col">Descripción</th>
          </tr>
        </thead>
        <tbody>
          <% @techs.where(tech_type: 'misc').each do |tech| %>
            <tr>
              <td>
                <%= image_tag('/assets/tech/misc', title: 'Otras tecnologías') %>
              </td>
              <td class="align-middle">
                <span class="font-weight-bold" style="font-size: 2em">
                  <%= tech.try(:lvl) %>
                </span>
              </td>
              <td class="align-middle">
                <%= tech.try(:name) %>
              </td>
              <td class="align-middle">
                <%= tech.try(:desc) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="tab-pane fade" id="nav-old" role="tabpanel" aria-labelledby="nav-old-tab">
      <table class="table table-responsive table-dark table-striped table-borderless table-hover table-sm table-responsive sortable">
        <caption>Tecnologías obsoletas</caption>
        <thead>
          <tr>
            <th scope="col">Rama</th>
            <th scope="col">Nivel</th>
            <th scope="col">Nombre</th>
            <th class='w-100' scope="col">Descripción</th>
          </tr>
        </thead>
        <tbody>
          <% @techs.where.not(tech_type: 'misc').each do |tech| %>
            <% if tech.obsolete %>
              <tr>
                <td>
                  <%= image_tag('/assets/tech/' + tech.tech_type.to_s, title: $tech_types[tech.tech_type.to_sym]) %>
                </td>
                <td class="align-middle">
                  <span class="font-weight-bold" style="font-size: 2em">
                    <%= tech.try(:lvl) %>
                  </span>
                </td>
                <td class="align-middle">
                  <%= tech.try(:name) %>
                </td>
                <td class="align-middle">
                  <%= tech.try(:desc) %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

    <% if current_user.try(:is_master?) then %>
      <div class="tab-pane fade" id="nav-add" role="tabpanel" aria-labelledby="nav-add-tab">
        <% tech = Tech.new %>
        <%= form_with(model: tech, local: true) do |form| %>
          <% if tech.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(tech.errors.count, "error") %> prohibited this army from being saved:</h2>
              <ul>
                <% tech.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group form-inline bottom-separator">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <div class="input-group-text"><i class="fas fa-flask"></i>&nbsp;</div>
              </div>
              <%= form.text_field :name, class: "form-control", placeholder: "Nombre" %>
            </div>

            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <div class="input-group-text"><i class="fab fa-ethereum"></i>&nbsp;</div>
              </div>
              <%= form.number_field :lvl, class: "form-control", style: "width: 90px", value: 0, min: 0 %>
            </div>

            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <div class="input-group-text"><i class="fas fa-cogs"></i>&nbsp;</div>
              </div>
              <%= form.select :tech_type, options_for_select($tech_types.invert(), 'misc'), {}, class: "custom-select" %>
            </div>
            <div class="input-group mb-3 w-100">
              <%= form.text_area :desc, rows: 5, id: 'desc', class: "custom-control w-100", placeholder: 'Descripción' %>
            </div>
          </div>

          <div class="input-group mb-3">
            <%= form.number_field :house_id, value: @civ.id, class: 'd-none' %>
            <%= form.submit class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
<% provide(:title, $all_tools.find_by(path: request.fullpath).title) %>
<% provide(:icon, $all_tools.find_by(path: request.fullpath).icon) %>

<div class="tool-title">
    <i class="white <%= yield(:icon) %>"></i>
    <%= yield(:title) %>
</div>

<% if current_user.try(:is_master?) then %>
  <nav>
    <div class="nav nav-pills mb-1" id="nav-tab" role="tablist">
      <% @civilizations.each do |civ| %>
        <a class="nav-item nav-link <%= civ == @civilizations.first ? 'active' : '' %>" id="nav-<%= civ.name %>-tab" data-toggle="tab" href="#nav-<%= civ.name %>" role="tab" aria-controls="nav-<%= civ.name %>" aria-selected="false"><%= civ.name %></a>
      <% end %>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <% @civilizations.each do |civ| %>
      <div class="tab-pane fade <%= civ == @civilizations.first ? 'active show' : '' %>" id="nav-<%= civ.name %>" role="tabpanel" aria-labelledby="nav-<%= civ.name %>-tab">
        <% @resource = civ.resource %>
        <% @systems = civ.systems %>
        <div class='container row'>
          <div class="float-left col-1 mt-4">
            <%= link_to '', dashboard_tech_path(id: civ), remote:true, class: 'white display-4 mb-3 fas fa-flask' %>
            <%= link_to '', dashboard_tech_path(id: civ), remote:true, class: 'white display-4 mb-3 fas fa-pencil-ruler' %>
          </div>
          <%= render 'dashboard' %>
          <%= render 'controls' %>
        </div>
        <%= render 'systems_table' %>
      </div>
    <% end %>
  </div>
<% else %>
<div class="float-left col-1 mt-4">
  <%= link_to '', dashboard_tech_path(id: current_user.house), remote:true, class: 'white display-4 mb-3 fas fa-flask' %>
  <%= link_to '', dashboard_tech_path(id: current_user.house), remote:true, class: 'white display-4 mb-3 fas fa-pencil-ruler' %>
</div>
  <%= render 'dashboard' %>
  <%= render 'systems_table' %>
<% end %>

<!-- Modal -->

<div class="modal fade" id="sectorModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div id='sector-content' class="modal-content bg-dark">
    </div>
  </div>
</div>

<div class="modal fade" id="techModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div id='tech-content' class="modal-content bg-dark">
    </div>
  </div>
</div>

app/views/dashboard/notes.js.erb
$('#sector-content').html("<%= j render 'notes', sectorhouse: @sectorhouse %>");
$('#sectorModal').modal('show');

app/views/dashboard/tech.js.erb
$('#tech-content').html("<%= j render 'techs', techs: @techs %>");
$('#techModal').modal('show');

$(".nav-item").click(function(){
  $("#nav-add-tab").removeClass('d-none');
});

$("#nav-add-tab").click(function(){
  $("#nav-add-tab").addClass('d-none');
});