config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :users, :except => [:new, :destroy]
  # patch '/users/:id/password', to: 'users#password', as: 'password'
  # post 'users/(/:id)/password', to: 'users#password', as: 'password'

  resources :houses, :except => [:show]

  resources :armies, :except => [:show] do
    collection do
      put 'update_multiple'
      put 'destroy_multiple'
      post 'edit_multiple'
      post 'import'
    end
  end
  get '/armies/:id/notes', to: 'armies#notes', as: 'army_note'
  get '/armies/:id/confirm', to: 'armies#confirm', as: 'army_confirm'

  # Login and logout routes
  get 'sso', to: 'sessions#sso', as: 'sso'

  post 'login', to: 'sessions#create', as: 'login'
  post 'logout', to: 'sessions#destroy', as: 'logout'
  get 'logout_sso', to: 'sessions#destroy_sso', as: 'logout_sso'

  resources :locations

  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get '/map', to: 'map#index'

  # get 'missions/', to: 'missions#index'
  # post 'missions/calculate', to: 'missions#calculate'
  # get 'missions/recipe', to: 'missions#recipe'

  get 'rep', to: 'reputations#index'
  post 'rep/change', to: 'reputations#change'

  get 'travel_calculator', to: 'travel_calculator#index'
  post 'travel_calculator/calculate', to: 'travel_calculator#calculate'
  # get 'travel_calculator/location_list', to: 'travel_calculator#location_list'

  # Render JSON lists for autocomplete

  get 'location_list', to: 'application#location_list'
  get 'location_list_en', to: 'application#location_list_en'
  get 'family_list', to: 'application#family_list'

  # Games and Tools

  get 'game', to: 'game#index'
  post 'game', to: 'game#set_active_game', as: 'set_active_game'

  resources :tools, :only => [:edit, :update]

  get '/ap-map', to: 'hex_map#index'

  resources :sectors, :except => [:show]
  delete '/sector_houses', to: 'sectors#sector_houses_destroy', as: 'delete_sector_houses'
  post '/sector_houses', to: 'sectors#sector_houses_create', as: 'create_sector_houses'

  post 'login_nemo', to: 'sessions#create_nemo', as: 'login_nemo'
  post 'login_master', to: 'sessions#create_master', as: 'login_master'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/notes', to: 'dashboard#notes', as: 'sector_note'
  post 'dashboard/notes', to: 'dashboard#notes_save', as: 'sector_note_save'
  post 'dashboard/resources/:id/spend', to: 'dashboard#spend_resources', as: 'spend_resources'
  post 'dashboard/resources/:id/efficiencies', to: 'dashboard#change_efficiencies', as: 'change_efficiencies'
  get 'dashboard/tech/:id', to: 'dashboard#tech', as: 'dashboard_tech'

  resources :techs, :except => [:show]
  get '/techs/:id/confirm', to: 'techs#confirm', as: 'tech_confirm'

  get '/designs/size_select', to: 'designs#size_select', as: 'size_select_design'
  post '/designs/new', to: 'designs#new', as: 'new_design'
  resources :designs, :except => [:new]
  get '/designs/:id/confirm', to: 'designs#confirm', as: 'design_confirm'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :tool
  accepts_nested_attributes_for :tool
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :admin_user

  def index
    @games = Game.all.order(:id)
    @tools = Tool.all.order(:sort).order(:id)
  end

  def set_active_game
    if params[:confirm] == 'SETUP'
      if Game.all.update(active: false) && Game.find_by(id: params[:game]).update(active: true)
        $tools = Tool.where(master: false, active: true).joins(:game).where(games: { active: true }).order(:sort).order(:id)
        $master_tools = Tool.where(master: true, active: true).joins(:game).where(games: { active: true }).order(:sort).order(:id)        
        redirect_to game_url
        flash[:success] = "La partida se ha inicializado correctamente"
      else
        redirect_to game_url
        flash[:danger] = "Se ha producido un error, por favor intentalo de nuevo."
      end
    else
      redirect_to game_url
      flash[:danger] = "Necesitas confirmar la acción para terminar la inicialización."
    end
  end

  # Check if user is admin
  def admin_user
    if current_user.nil?
      redirect_to root_url
      flash[:danger] = "Por favor, inicia sesión."
    elsif !current_user.is_admin?
      redirect_to(root_url)
      flash[:danger] = "No tienes permisos para acceder a esta página."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/index.html.erb
<% provide(:title, "Configuración de partida") %>
<% provide(:icon, "fas fa-tachometer-alt") %>

<div class="tool-title">
    <i class="white <%= yield(:icon) %>"></i>
    <%= yield(:title) %>
</div>

<div class="card bg-secondary mb-3">
  <div class="card-body">
    <div class="card-text text-center">
      <button type="button" id="newGameBtn" class="btn btn-warning btn-lg">Preparar partida nueva</button>
      <%= form_with url: set_active_game_path, remote: true do |form| %>
        <div id="newGameForm" class="form-group form-inline" style="display: none">
          <div style="position: absolute; right: 0px; top: 0px;">
            <button type="button" id="cancel" class="btn btn-link text-white"><i class="fas fa-times-circle"></i></button>
          </div>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Partida</div>
            </div>
            <%= form.select( :game, options_for_select(Hash[@games.map(&:title).zip(@games.map(&:id))]), {}, {class: "custom-select"}) %>
          </div>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Confirmar</div>
            </div>
            <%= form.text_field :confirm, class: "custom-control", placeholder: "Escribe 'SETUP' para confirmar" %>
          </div>
          <div class="input-group mb-2">
            <%= form.submit "Preparar", class: "btn btn-primary", id: "setup" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div>
  <table class="table table-dark table-striped table-borderless table-hover table-sm table-responsive sortable">
    <caption>Lista de partidas</caption>
      <thead>
        <tr>
          <th scope="col" class="sorter-false" colspan="2">Nombre</th>
          <th scope="col">Herramientas <i class="fas fa-sort"></i></th>
          <th scope="col" class="sorter-font-awesome">¿Activa? <i class="fas fa-sort"></i></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
          <tr>
            <td><%= image_tag('/assets/' + game.icon, class: 'game-icon') %></td>
            <td><%= game.title %></td>
            <td>
              <% tools = [] %>
              <% game.tool.each do |tool|  %>
                <% tools << tool.short_title %>
              <% end %>
              <%= tools.join(',') %>
            </td>
            <td class="text-center">
              <% if game.active == true  %>
                <i class="fas fa-check"></i>
              <% else %>
                <i class="fas fa-times"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>

  <table class="table table-dark table-striped table-borderless table-hover table-sm table-responsive sortable">
    <caption>Lista de herramientas</caption>
      <thead>
        <tr>
          <th scope="col" class="sorter-false" colspan="2">Nombre</th>
          <th scope="col">Partida <i class="fas fa-sort"></i></th>
          <th scope="col" class="sorter-font-awesome">¿Activa? <i class="fas fa-sort"></i></th>
          <th scope="col" class="sorter-font-awesome">¿Máster? <i class="fas fa-sort"></i></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @tools.each do |tool| %>
          <tr>
            <td><i class="<%= tool.icon %>"></i></td>
            <td><%= tool.short_title %></td>
            <td>
              <% games = [] %>
              <% tool.game.each do |game|  %>
                <% games << game.title %>
              <% end %>
              <%= games.join(',') %>
            </td>
            <td class="text-center">
              <% if tool.active == true  %>
                <i class="fas fa-check"></i>
              <% else %>
                <i class="fas fa-times"></i>
              <% end %>
            </td>
            <td class="text-center">
              <% if tool.master == true  %>
                <i class="fas fa-check"></i>
              <% else %>
                <i class="fas fa-times"></i>
              <% end %>
            </td>
            <td><%= link_to '', edit_tool_path(tool), remote: true, class: 'fas fa-edit white' %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

<!-- Modal -->

<div id='tool-content'></div>