config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :users, :except => [:new, :destroy]
  # patch '/users/:id/password', to: 'users#password', as: 'password'
  # post 'users/(/:id)/password', to: 'users#password', as: 'password'

  resources :houses, :except => [:show]

  resources :armies, :except => [:show] do
    collection do
      put 'update_multiple'
      put 'destroy_multiple'
      post 'edit_multiple'
      post 'import'
    end
  end
  get '/armies/:id/notes', to: 'armies#notes', as: 'army_note'
  get '/armies/:id/confirm', to: 'armies#confirm', as: 'army_confirm'

  # Login and logout routes
  get 'sso', to: 'sessions#sso', as: 'sso'

  post 'login', to: 'sessions#create', as: 'login'
  post 'logout', to: 'sessions#destroy', as: 'logout'
  get 'logout_sso', to: 'sessions#destroy_sso', as: 'logout_sso'

  resources :locations

  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get '/map', to: 'map#index'

  # get 'missions/', to: 'missions#index'
  # post 'missions/calculate', to: 'missions#calculate'
  # get 'missions/recipe', to: 'missions#recipe'

  get 'rep', to: 'reputations#index'
  post 'rep/change', to: 'reputations#change'

  get 'travel_calculator', to: 'travel_calculator#index'
  post 'travel_calculator/calculate', to: 'travel_calculator#calculate'
  # get 'travel_calculator/location_list', to: 'travel_calculator#location_list'

  # Render JSON lists for autocomplete

  get 'location_list', to: 'application#location_list'
  get 'location_list_en', to: 'application#location_list_en'
  get 'family_list', to: 'application#family_list'

  # Games and Tools

  get 'game', to: 'game#index'
  post 'game', to: 'game#set_active_game', as: 'set_active_game'

  resources :tools, :only => [:edit, :update]

  get '/ap-map', to: 'hex_map#index'

  resources :sectors, :except => [:show]
  delete '/sector_houses', to: 'sectors#sector_houses_destroy', as: 'delete_sector_houses'
  post '/sector_houses', to: 'sectors#sector_houses_create', as: 'create_sector_houses'

  post 'login_nemo', to: 'sessions#create_nemo', as: 'login_nemo'
  post 'login_master', to: 'sessions#create_master', as: 'login_master'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/notes', to: 'dashboard#notes', as: 'sector_note'
  post 'dashboard/notes', to: 'dashboard#notes_save', as: 'sector_note_save'
  post 'dashboard/resources/:id/spend', to: 'dashboard#spend_resources', as: 'spend_resources'
  post 'dashboard/resources/:id/efficiencies', to: 'dashboard#change_efficiencies', as: 'change_efficiencies'
  get 'dashboard/tech/:id', to: 'dashboard#tech', as: 'dashboard_tech'

  resources :techs, :except => [:show]
  get '/techs/:id/confirm', to: 'techs#confirm', as: 'tech_confirm'

  get '/designs/size_select', to: 'designs#size_select', as: 'size_select_design'
  post '/designs/new', to: 'designs#new', as: 'new_design'
  resources :designs, :except => [:new]
  get '/designs/:id/confirm', to: 'designs#confirm', as: 'design_confirm'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sector.rb
class Sector < ApplicationRecord
  has_many :sector_houses, :class_name => 'SectorHouse'
  has_many :houses, through: :sector_houses

  accepts_nested_attributes_for :sector_houses

  has_one :system
  accepts_nested_attributes_for :system

  validates_uniqueness_of :q, :scope => [:r]
  validates :q, :r, presence: true

  $sector_types = {'empty': 'Vacío', 'star-red': 'Estrella tipo K'}
  validates_inclusion_of :sector_type, :in => $sector_types.collect {|k,v| k.to_s}

end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :master_user
  before_action :set_sector, only: [:edit, :update, :notes]
  before_action :set_user_list, except: [:index, :update]

  def index
    @sectors = Sector.all.order(:id)

    abs_coords = []
    Sector.all.each do |x|
      abs_coords << x.r.abs
      abs_coords << x.q.abs
    end
    @hex_rings = ( abs_coords.max || 0 ) + 1

    @hex_map = {}
    Sector.all.each do |hex|
      @hex_map[hex.q] = {} if @hex_map[hex.q].nil?
      @hex_map[hex.q][hex.r] = {
        :type=> hex.sector_type
        }
    end

    respond_to do |format|
        format.html
        format.js
    end
  end

  # GET /sectors/1/edit
  def edit
    @available_factions = House.where.not(hid: 0).where(active: true).where.not(id: @sector.houses.pluck(:id))
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
    @available_factions = House.where.not(hid: 0).where(active: true).where.not(id: @sector.houses.pluck(:id))
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params.except(:new_sector))
        format.html { redirect_to request.referrer, success: 'Sector editado correctamente.' }
      else
        format.html { redirect_to request.referrer, danger: @sector.errors }
      end
    end
  end

  def sector_houses_destroy
    @sector = Sector.find(params[:sector_id])
    @sector_house = @sector.sector_houses.find(params[:id])

    if @sector.try(:system).try(:house) == @sector_house.house
      @forbidden = true
    else
      @forbidden = false
      @sector_house.destroy
    end

    @action = 'destroy'

    @available_factions = House.where.not(hid: 0).where(active: true).where.not(id: @sector.houses.pluck(:id))

    respond_to do |format|
      format.js { render :sector_users }
    end
  end

  def sector_houses_create
    @sector = Sector.find(params[:sector_id])
    @house = params[:house_id].nil? ? nil : House.find(params[:house_id])

    if @house.nil?
      @forbidden = true
    else
      @forbidden = false
      @sector.houses << @house
    end

    @action = 'create'

    @available_factions = House.where.not(hid: 0).where(active: true).where.not(id: @sector.houses.pluck(:id))

    respond_to do |format|
      format.js { render :sector_users }
    end
  end

  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to sectors_url, success: 'Sector añadido correctamente.' }
      else
        format.html { redirect_to sectors_url, danger: @sector.errors }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    def set_user_list
      @house_list = House.where(hid: 0)
    end

    def master_user
      if current_user.nil?
        flash[:danger] = "Por favor, inicia sesión."
        redirect_to root_url
      elsif !current_user.is_master? && !current_user.is_admin?
        redirect_to(root_url)
        flash[:danger] = "No tienes permisos para acceder a esta página."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:name, :q, :r, :sector_type, :notes, :desc, :sector_houses_attributes => [:id, :info, :notes, :user_id], :new_sector => [:user_id, :info], :system_attributes => [:id, :house_id, :slots, :ic_slots, :ic_bonus, :rp_slots, :rp_bonus, :cp_slots, :cp_bonus, :mc_slots, :efficiency, :unrest])
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_with(model: sector, local: true) do |form| %>
  <div class="modal-header">
    <h5 class="modal-title" id="Title"><%= form.text_field(:name, id: 'name', class: "custom-control", placeholder: 'Nombre del sector') %></h5>
    <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <% if sector.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>
        <ul>
          <% sector.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group form-inline bottom-separator">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="fas fa-hashtag"></i>&nbsp;</div>
        </div>
        <%= form.number_field :id, id: 'id', style: "width: 90px", class: "custom-control", disabled: true, value: sector.id %>
      </div>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <div class="input-group-text">q</div>
        </div>
        <%= form.number_field :q, id: 'q', style: "width: 90px", class: "custom-control", required: 'required' %>
      </div>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <div class="input-group-text">r</div>
        </div>
        <%= form.number_field :r, id: 'r', style: "width: 90px", class: "custom-control", required: 'required' %>
      </div>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <div class="input-group-text"><i class="fas fa-sun"></i>&nbsp;</div>
        </div>
        <%= form.select :sector_type, options_for_select($sector_types.invert(), sector.sector_type), {}, id: 'sector_type', class: "custom-select" %>
      </div>
      <div class="input-group mb-3 w-100">
        <%= form.text_area :desc, rows: 5, id: 'desc', class: "custom-control w-75", placeholder: 'Descripción' %>
      </div>
      <div class="input-group mb-3 w-100">
        <%= form.text_area :notes, rows: 5, id: 'notes', class: "custom-control w-75", placeholder: 'Notas del master', style: 'background: lightyellow' %>
      </div>
    </div>

    <% if @sector.id %>
      <div class="row bottom-separator mb-3">
        <div class="col-md-6 right-separator">
          <h3>Visibilidad</h3>
          <%= form.fields_for :sector_houses do |form| %>
            <div id="form_<%= form.object.id %>">
              <div id="main_<%= form.object.id %>" class="form-group mb-1">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div style="width: 180px; display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis" class="input-group-text text-left"><%= raw '<i class="fas fa-flag-checkered"></i>&nbsp;' unless form.object.info_lvl != 'Colonizado' %><%= House.find_by(id: form.object.house_id).name%></div>
                  </div>
                  <%= form.number_field :info, max: 3, min: 0, style: "width: 90px", class: "custom-control" %>
                  <%= form.button '<i class="fas fa-sticky-note"></i>'.html_safe, type: 'button', id: "notes_btn_" + form.object.id.to_s , class: 'notes ' + (form.object.notes.nil? || form.object.notes.empty? ? "btn btn-secondary" : "btn btn-success") %>
                  <%= form.button '<i class="fas fa-trash-alt"></i>'.html_safe, type: 'button', id: "delete_btn_" + form.object.id.to_s, class: 'delete btn btn-danger' %>
                </div>
              </div>
              <div id='delete_confirm_<%=form.object.id.to_s%>' class="form-group mb-3" style='display: none'>
                <%= link_to '<i class="fas fa-trash-alt"></i> Confirma el borrado'.html_safe, delete_sector_houses_path(sector_id: form.object.sector_id,id: form.object.id), method: :delete, remote:true, class: "btn btn-danger" %>
                <%= form.button '<i class="fas fa-times-circle"></i>'.html_safe, type: 'button', id: "delete_cancel_" + form.object.id.to_s, class: 'cancel btn btn-secondary' %>
              </div>
              <div id='notes_box_<%=form.object.id.to_s%>' class="form-group mb-3" style='display: none'>
                <%= form.text_area :notes, rows: 5, class: "custom-control w-100", placeholder: 'Notas del jugador' %>
              </div>
            </div>
          <% end %>

          <% if @available_factions.empty? == false %>
            <%= link_to '<i class="fas fa-plus-circle"></i> Añadir Jugador'.html_safe, create_sector_houses_path(sector_id: sector.id), method: :post, remote: true, id: 'new_user_link', class: 'btn btn-success', data: { sector_id: sector.id} %>
            <%= select_tag :new_user, options_for_select(@available_factions.pluck(:name, :id)), include_blank: true, style: "width: 160px", id: 'new_user_select', class: "custom-select" %>
          <% end %>
        </div>

        <div class="col-md-6">
          <div class="row ml-1 mb-2">
            <h3>Sistema</h3>
            <div class="ml-auto mr-3">
              <%= form.button sector.system.nil? ? '<i class="fas fa-plus-circle"></i> Añadir Sistema'.html_safe : '<i class="fas fa-plus-circle"></i> Editar Sistema'.html_safe, type: 'button', id: "edit_system", class: "btn btn-success" %>
              <%= form.button '<i class="fas fa-times-circle"></i> Cancelar'.html_safe , type: 'button', id: "cancel_system", class: "btn btn-secondary", style: 'display:none'  %>
            </div>
          </div>
          <%= form.fields_for :system, sector.system || System.new do |form| %>
            <div id="system" class="op-20">
              <div id="slots_free"></div>
              <div class="input-group mb-1">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-flag-checkered"></i>&nbsp;</div>
                </div>
                <%= form.select :house_id, options_for_select(sector.houses.map {|x| [x.name + ' (' +  x.users.pluck(:player).join(',') + ')',x.id] }, sector.system.nil? ? nil : sector.system.house_id ), {include_blank: true}, disabled: true, class: "custom-select" %>
              </div>
              <div class="input-group mb-1">
                <div class="input-group-prepend">
                  <div class="input-group-text">Habitabilidad base</div>
                </div>
                <%= form.number_field :slots, min:0, style: "width: 120px", disabled: true, id: "slots", class: "custom-control" %>
              </div>
              <div class="form-group form-inline mb-0">
                <div class="input-group mb-1">
                  <div class="input-group-prepend">
                    <div style="width: 42.45px" class="input-group-text"><i class="fas fa-industry"></i>&nbsp;</div>
                  </div>
                  <%= form.number_field :ic_slots, min:0, disabled: true, style: "width: 90px", id: "ic_slots", class: "custom-control" %>
                </div>
                <div class="input-group mb-1">
                  <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fas fa-percentage"></i>&nbsp;</div>
                  </div>
                  <%= form.number_field :ic_bonus, min:0.00, step: 0.01, disabled: true, style: "width: 100px", id: "ic_slots", class: "custom-control" %>
                </div>
              </div>
              <div class="form-group form-inline mb-0">
                <div class="input-group mb-1">
                  <div class="input-group-prepend">
                    <div style="width: 42.45px" class="input-group-text"><i class="fas fa-flask"></i>&nbsp;</div>
                  </div>
                  <%= form.number_field :rp_slots, min:0, disabled: true, style: "width: 90px", id: "rp_slots", class: "custom-control" %>
                </div>
                <div class="input-group mb-1">
                  <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fas fa-percentage"></i>&nbsp;</div>
                  </div>
                  <%= form.number_field :rp_bonus, min:0.00, step: 0.01, disabled: true, style: "width: 100px", id: "ic_slots", class: "custom-control" %>
                </div>
              </div>
              <div class="form-group form-inline mb-0">
                <div class="input-group mb-1">
                  <div class="input-group-prepend">
                    <div style="width: 42.45px" class="input-group-text"><i class="fas fa-chess-king"></i>&nbsp;</div>
                  </div>
                  <%= form.number_field :cp_slots, min:0, disabled: true, style: "width: 90px", id: "cp_slots", class: "custom-control" %>
                </div>
                <div class="input-group mb-1">
                  <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fas fa-percentage"></i>&nbsp;</div>
                  </div>
                  <%= form.number_field :cp_bonus, min:0.00, step: 0.01, disabled: true, style: "width: 100px", id: "ic_slots", class: "custom-control" %>
                </div>
              </div>
              <div class="form-group form-inline mb-0">
                <div class="input-group mb-1">
                  <div class="input-group-prepend">
                    <div style="width: 42.45px" class="input-group-text"><i class="fas fa-star"></i>&nbsp;</div>
                  </div>
                  <%= form.number_field :mc_slots, min:0, disabled: true, style: "width: 90px", id: "mc_slots", class: "custom-control" %>
                </div>
              </div>
              <div class="input-group mb-1">
                <div class="input-group-prepend">
                  <div class="input-group-text">Global&nbsp;<i class="fas fa-percentage"></i></div>
                </div>
                <%= form.number_field :efficiency, min:0.00, step: 0.01, disabled: true, style: "width: 100px", id: "efficiency", class: "custom-control" %>
              </div>
              <div class="input-group mb-1">
                <div class="input-group-prepend">
                  <div class="input-group-text"><i class="fas fa-fist-raised"></i>&nbsp;</div>
                </div>
                <%= form.number_field :unrest, min:0, disabled: true, class: "custom-control" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="form-group form-inline">
      <%= form.submit class: "btn btn-primary" %>
    </div>

  </div>
<% end %>

app/views/sectors/_sectors.js.erb
$(document).on('turbolinks:load', function () {
  if ($(".sectors.index").length !== 0 ) {
    if ($('#hex').data('loaded') == false) {

      var hex_map = <%= @hex_map.to_json.html_safe %>

      $('#hex').hexGridWidget(15, <%= @hex_rings %>, 'hexfield hex_unknown', 'd-none');

      for (var q of Object.keys(hex_map)) {
        for (var r of Object.keys(hex_map[q])) {
          $('#' + q + '_' + r).removeClass('hex_unknown');
          $('#' + q + '_' + r).addClass('hex_' + hex_map[q][r]['type']);
        }
      }

      $('#hex').data('loaded', true);

    }
  }
});

app/views/sectors/_update.js.erb
$('.notes').on('click',
  function () {
    var id = $(this).attr('id').substring(10,50);
    if ($(this).hasClass('clicked') == false) {
      $(this).addClass('clicked')
      $('#notes_box_' + id).slideDown(350);
    } else {
      $(this).removeClass('clicked')
      $('#notes_box_' + id).hide();
    }
  });

$('.delete').on('click',
  function () {
    var id = $(this).attr('id').substring(11,50);
    $('#delete_confirm_' + id).slideDown(350);
    $('#main_' + id).addClass('op-20');
    $('#main_' + id + ' :input').attr('disabled', true);
  });

$('.cancel').on('click',
  function () {
    var id = $(this).attr('id').substring(14,50);
    $('#delete_confirm_' + id).hide();
    $('#main_' + id).removeClass('op-20');
    $('#main_' + id + ' :input').attr('disabled', false);
  });

$('#new_user_select').on('change',
  function () {
    var sector_id = $('#new_user_link').data('sectorId');
    var house_id = this.value
    var url = '<%= create_sector_houses_path %>' + '?sector_id=' + sector_id + '&house_id=' + house_id

    $('#new_user_link').attr('href', url);
  });

$('#edit_system').on('click',
  function () {
    $(this).hide();
    $('#system :input').attr('disabled', false)
    $('#system').removeClass('op-20');
    $('#cancel_system').show();
  });

$('#cancel_system').on('click',
  function () {
    $(this).hide();
    $('#system :input').attr('disabled', true);
    $('#system').addClass('op-20');
    $('#edit_system').show();
  });

$('#ic_slots,#rp_slots,#cp_slots').on('change',
  function (e){
    var ic = parseInt($('#ic_slots').val())
    var rp = parseInt($('#rp_slots').val())
    var cp = parseInt($('#cp_slots').val())
    var mc = parseInt($('#mc_slots').val())
    var slots_free = $('#slots').val() - (ic + rp + cp + mc)
    if (slots_free >= 0) {
      $('#slots_free').html()
    }
    else {
      $('#slots_free').html(`<div class="container mx-auto text-center alert alert-danger">La población no puede ser superior a la habitabilidad. Elimina ` + (slots_free * -1) + `M de población</div>`);
    }
  });

app/views/sectors/edit.js.erb
$('#sector-content').html("<%= j render 'form', sector: @sector %>");
<%=  render 'update' %>
$('#sectorModal').modal('show');

app/views/sectors/index.html.erb
<% provide(:title, $all_tools.find_by(path: request.fullpath).title) %>
<% provide(:icon, $all_tools.find_by(path: request.fullpath).icon) %>

<div class="tool-title">
    <i class="white <%= yield(:icon) %>"></i>
    <%= yield(:title) %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-auto">
      <div id='hex' data-loaded="false">
        <svg id='canvas'>
          <defs>
            <pattern id="unknown" height="100%" width="100%" patterncontentunits="objectBoundingBox">
              <image width="1" height="1" preserveaspectratio="none" href="assets/hex/bg-unknown.png"></image>
            </pattern>
            <pattern id="star-red" height="100%" width="100%" patterncontentunits="objectBoundingBox">
              <image width="1" height="1" preserveaspectratio="none" href="assets/hex/bg-star-red.png"></image>
            </pattern>
            <pattern id="empty" height="100%" width="100%" patterncontentunits="objectBoundingBox">
              <image width="1" height="1" preserveaspectratio="none" href="assets/hex/bg-empty.png"></image>
            </pattern>
          </defs>
        </svg>
      </div>
    </div>
    <div class="col">
      <div>
        <table class="table table-dark table-striped table-borderless table-hover table-sm table-responsive sortable">
          <caption>Lista de sectores</caption>
            <thead>
              <tr>
                <th scope="col">Sector <i class="fas fa-sort"></i></th>
                <th scope="col">Posición <i class="fas fa-sort"></i></th>
                <th scope="col">Tipo <i class="fas fa-sort"></i></th>
                <th scope="col">Visibilidad <i class="fas fa-sort"></i></th>
                <th scope="col">Civilización <i class="fas fa-sort"></i></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% @sectors.each do |sector| %>
                <tr id='<%= 'row_' + sector.q.to_s + '_' + sector.r.to_s %>' class='row_hover'>
                  <td><%= sector.name %></td>
                  <td><%= sector.q.to_s + ',' + sector.r.to_s %></td>
                  <td><%= $sector_types[sector.sector_type.to_sym] %></td>
                  <td id="visibility_list_<%= sector.id %>"><%= sector.sector_houses.order('info DESC').map{|x| [x.house.name, ' (' + x.info_lvl.to_s + ')'].join('')}.join(', ').html_safe %></td>
                  <% if sector.system.nil? || sector.system.house.nil? then %>
                    <td></td>
                  <% else %>
                    <td><%= sector.system.house.name + ' (' + sector.system.house.users.pluck(:player).join(',') + ')' %></td>
                  <% end %>
                  <% if current_user.try(:is_master?) then %>
                    <td><%= link_to '', edit_sector_path(sector), remote: true, class: 'fas fa-edit white' %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>

      <% if current_user.try(:is_master?) then %>
        <div><%= link_to '<i class="fas fa-plus-circle"></i> Añadir sector'.html_safe, new_sector_path, remote:true, class: "btn btn-primary"%></div>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal -->

<div class="modal fade" id="sectorModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div id='sector-content' class="modal-content bg-dark">
    </div>
  </div>
</div>

<script>
  <%= render 'sectors.js' %>
</script>

app/views/sectors/new.js.erb
$('.bg-warning').removeClass('bg-warning');
$('#sector-content').html("<%= j render 'form', sector: @sector %>");
<%=  render 'update' %>
$('#sectorModal').modal('show');

if ($('.hex-selected').hasClass('hex_unknown')) {
  $("[name='sector[q]']").val( $('.hex-selected').attr('q') );
  $("[name='sector[r]']").val( $('.hex-selected').attr('r') )
}

app/views/sectors/sector_users.js.erb
var inputs = {}
$(":input").each(function(){
  var e = $(this).attr('id');
  var val = $(this).val();
  inputs[e] = val
});

if ($('#cancel_system').is(":visible")) {
  var edit = true;
} else {
  var edit = false;
}

$('#sector-content').html("<%= j render 'form', sector: @sector %>");

<%=  render 'update' %>

for (var key in inputs){
  $('#' + key).val(inputs[key])
}

if (edit) {
  $('#edit_system').hide();
  $('#system :input').attr('disabled', false);
  $('#system').removeClass('op-20');
  $('#cancel_system').show();
}

$('#visibility_list_' + <%= @sector.id %>).html("<%= @sector.sector_houses.order('info DESC').map{|x| [x.house.name, ' (' + x.info_lvl.to_s + ')'].join('')}.join(',').html_safe %>")

if ('<%= @action %>' == 'create') {
  if (<%= @forbidden %>) {
    $('.modal-body').prepend(`<div class="container mx-auto text-center alert alert-danger">Selecciona una facción para crear la relación.</div>`);
  } else {
    $('.modal-body').prepend(`<div class="container mx-auto text-center alert alert-success">Relación creada correctamente.</div>`);
  }
}

if ('<%= @action %>' == 'destroy') {
  if (<%= @forbidden %>) {
    $('.modal-body').prepend(`<div class="container mx-auto text-center alert alert-danger">El controlador del sistema no puede ser eliminado.</div>`);
  } else {
    $('.modal-body').prepend(`<div class="container mx-auto text-center alert alert-success">Relación eliminada correctamente.</div>`);
  }
}